//go:build e2e

package e2etests_test

import (
	"context"
	"testing"
	"time"

	"cloud.google.com/go/osconfig/apiv1/osconfigpb"
	"github.com/GoogleCloudPlatform/osconfig/e2e_tests_v2/internal/gcp"
	"github.com/GoogleCloudPlatform/osconfig/e2e_tests_v2/internal/inventoryassert"
	"github.com/GoogleCloudPlatform/osconfig/e2e_tests_v2/internal/scenario"
	"github.com/GoogleCloudPlatform/osconfig/e2e_tests_v2/internal/testenv"
)

// TestFunctionalInventoryReporting is a reduced form of the original
// OSInventoryReporting suite. It checks fresh inventory identity and concrete
// installed-package records on two candidate-image platform implementations.
func TestFunctionalInventoryReporting(t *testing.T) {
	cases := []scenario.Case{
		{
			ID: "functional/inventory-reporting/debian-12", Feature: "inventory-reporting",
			Category: scenario.Functional, Platform: "debian-12", ImageKey: "functional-debian-12",
			ExpectedShortName: "debian",
			ExpectedPackages: []scenario.Package{
				{Manager: scenario.APT, Name: "bash"},
				{Manager: scenario.APT, Name: "google-osconfig-agent"},
			},
		},
		{
			ID: "functional/inventory-reporting/el9", Feature: "inventory-reporting",
			Category: scenario.Functional, Platform: "el9", ImageKey: "functional-el9",
			ExpectedShortName: "rhel",
			ExpectedPackages: []scenario.Package{
				{Manager: scenario.YUM, Name: "bash"},
				{Manager: scenario.YUM, Name: "google-osconfig-agent"},
			},
		},
	}
	for _, testCase := range cases {
		testCase := testCase
		runScenario(t, testCase, func(t *testing.T, env *testenv.Environment) {
			createdAfter := time.Now()
			var vm *gcp.VM
			env.Step("create isolated candidate VM", func(ctx context.Context) error {
				var err error
				vm, err = env.CreateVM(ctx)
				return err
			})

			var inventory *osconfigpb.Inventory
			env.Step("wait for inventory generated by this VM", func(ctx context.Context) error {
				var err error
				inventory, err = env.WaitForInventory(ctx, *vm, createdAfter)
				return err
			})
			env.Step("assert hostname, OS, and installed package inventory", func(context.Context) error {
				return inventoryassert.Check(inventory, vm.Name, testCase.ExpectedShortName, testCase.ExpectedPackages)
			})
		})
	}
}
