//go:build e2e

package e2etests_test

import (
	"context"
	"fmt"
	"testing"

	"cloud.google.com/go/osconfig/apiv1/osconfigpb"
	"github.com/GoogleCloudPlatform/osconfig/e2e_tests_v2/internal/gcp"
	"github.com/GoogleCloudPlatform/osconfig/e2e_tests_v2/internal/inventoryassert"
	"github.com/GoogleCloudPlatform/osconfig/e2e_tests_v2/internal/scenario"
	"github.com/GoogleCloudPlatform/osconfig/e2e_tests_v2/internal/testenv"
)

// TestAgentInstallAndUpgrade keeps one installation backend and one exact
// starting-version upgrade. The startup operation validates package digest,
// installed version, service enablement, and service activity before reporting
// success; the body then requires inventory generated by that installed agent.
func TestAgentInstallAndUpgrade(t *testing.T) {
	cases := []scenario.Case{
		{
			ID: "install-upgrade/install/debian-12", Feature: "agent-installation",
			Category: scenario.InstallUpgrade, Platform: "debian-12", ImageKey: "public-debian-12",
			ExpectedShortName: "debian", Bootstrap: scenario.InstallDEB,
			ExpectedPackages: []scenario.Package{{Manager: scenario.APT, Name: "google-osconfig-agent"}},
		},
		{
			ID: "install-upgrade/upgrade/el9", Feature: "agent-upgrade",
			Category: scenario.InstallUpgrade, Platform: "el9", ImageKey: "public-el9",
			ExpectedShortName: "rhel", Bootstrap: scenario.UpgradeRPM,
			ExpectedPackages: []scenario.Package{{Manager: scenario.YUM, Name: "google-osconfig-agent"}},
		},
	}
	for _, testCase := range cases {
		testCase := testCase
		runScenario(t, testCase, func(t *testing.T, env *testenv.Environment) {
			var vm *gcp.VM
			env.Step("create VM from unmodified public image", func(ctx context.Context) error {
				var err error
				vm, err = env.CreateVM(ctx)
				return err
			})

			var bootstrap testenv.BootstrapResult
			env.Step("verify package lifecycle and running service", func(ctx context.Context) error {
				var err error
				bootstrap, err = env.WaitForBootstrap(ctx, *vm)
				if err != nil {
					return err
				}
				if bootstrap.Current != expectedBootstrapVersion(testCase) {
					return fmt.Errorf("installed version=%q want=%q", bootstrap.Current, expectedBootstrapVersion(testCase))
				}
				if testCase.Bootstrap == scenario.UpgradeRPM && bootstrap.Previous != e2eSuite.Config.RPMUpgradeFrom {
					return fmt.Errorf("upgrade starting version=%q want=%q", bootstrap.Previous, e2eSuite.Config.RPMUpgradeFrom)
				}
				return nil
			})

			var inventory *osconfigpb.Inventory
			env.Step("verify installed agent reports fresh inventory", func(ctx context.Context) error {
				var err error
				inventory, err = env.WaitForInventory(ctx, *vm, bootstrap.ObservedAt)
				if err != nil {
					return err
				}
				return inventoryassert.Check(inventory, vm.Name, testCase.ExpectedShortName, testCase.ExpectedPackages)
			})
		})
	}
}
